[package]
name = "claude-api-interaction"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "claude-api-interaction"
path = "src/main.rs"

[lib]
name = "claude_api_interaction"
path = "src/lib.rs"

[dependencies]                                                             
security-framework = "3.0.0" 
anthropic = { version = "0.0.8", features = ["native-tls"], default-features = false }
tokio = { version = "1.25.0", features = ["full"] }
env_logger = "0.11.5"
log = "0.4.17"
anyhow = "1.0"
once_cell = "1.17.1"
chrono = "0.4.38"
csv = "1.3.0"
futures = "0.3"
reqwest = { version = "0.12.8", features = ["json"]}
sled = "0.34"
url = "2.5.2"
chardet = "0.2"
encoding_rs = "0.8.34"
encoding_rs_io = "0.1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.128"
regex = "1.5"
html-escape = "0.2"
uuencode = "0.1.5"
radixdb = "0.2.5"
rustyline = "14.0.0"
rustyline-derive = "0.10.0"
scraper = "0.20.0"


[dev-dependencies]
tempfile = "3.2"
