[package]
name = "claude-api-interaction"
version = "0.1.0"
edition = "2021"

[dependencies]                                                             
security-framework = "3.0.0" 
anthropic = { version = "0.0.8", features = ["native-tls"], default-features = false }
tokio = { version = "1.25.0", features = ["full"] }
env_logger = "0.11.5"
log = "0.4.17"
dotenv = "0.15.0"
sec_edgar = "1.0.5"
anyhow = "1.0"
once_cell = "1.17.1"
