[package]
name = "claude-api-interaction"
version = "0.1.0"
edition = "2021"

[dependencies]                                                             
security-framework = "3.0.0" 
anthropic = { version = "0.0.8", features = ["native-tls"], default-features = false }
tokio = { version = "1.25.0", features = ["full"] }
env_logger = "0.11.5"
log = "0.4.17"
anyhow = "1.0"
once_cell = "1.17.1"
chrono = "0.4.38"
csv = "1.3.0"
reqwest = { version = "0.12.8", features = ["json"]}
url = "2.5.2"