version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    image: advisor:${VERSION:-latest}
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/advisor
    depends_on:
      db:
        condition: service_healthy

  db:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=advisor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  cargo-cache:
    driver: local
