version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: .docker/Dockerfile.dev
      target: base
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/advisor
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - openai_key

  db:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: advisor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  cargo-cache:

secrets:
  openai_key:
    file: .secrets/openai_key.txt
  db_password:
    file: .secrets/db_password.txt
