version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: .docker/Dockerfile.dev
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
    network_mode: service:qdrant

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
