version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: .docker/Dockerfile.dev
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
      - OPENAI_KEY=${OPENAI_KEY}
      - DATABASE_URL=postgres://postgres:postgres@db:5432/advisor

  db:
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=advisor
    command: >
      bash -c "psql -U postgres -d advisor -c 'CREATE EXTENSION IF NOT EXISTS vector;' && postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
