version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: .docker/Dockerfile.dev
    volumes:
      - .:/workspace:cached
    command: cargo run
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
      - OPENAI_KEY=${OPENAI_KEY}
      - DATABASE_URL=postgres://postgres:postgres@db:5432/advisor

  db:
    image: pgvector/pgvector:pg17
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=advisor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    command: /workspace/target/release/advisor
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/advisor
      - RUST_LOG=debug
    depends_on:
      - db

  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: advisor
    ports:
      - "5432:5432"

volumes:
  postgres-data:
