version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: .docker/Dockerfile.dev
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/advisor
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=advisor
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
version: '3.8'

services:
  advisor:
    build: .
    environment:
      - OPENAI_KEY=${OPENAI_KEY}
      - QDRANT_URI=http://qdrant:6334
    depends_on:
      - qdrant
    volumes:
      - ./data:/app/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
