version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: .docker/Dockerfile.dev
    volumes:
      - ..:/workspace:cached
    command: cargo run
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
      - OPENAI_KEY=${OPENAI_KEY}
      - DATABASE_URL=postgres://postgres:postgres@db:5432/advisor
    depends_on:
      db:
        condition: service_healthy

  db:
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=advisor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
